name = "playground-games"
main = "worker.js"
compatibility_date = "2026-02-22"
account_id = "02a72e7b05b30f0f0831470b7e7eb4d3"

routes = [
  { pattern = "ws.tinglingding.win", zone_name = "tinglingding.win" }
]

[[durable_objects.bindings]]
name = "GAME_ROOM"
class_name = "GameRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = [ "GameRoom" ]

[vars]
